services:
  discovery-server:
    image: discovery-server
    container_name: discovery-server
    build:
      context: infra/discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: infra/config-server
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=config-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/CONFIG-SERVER || exit 1
      interval: 30s
      timeout: 5s
      start_period: 60s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy

  gateway-server:
    image: gateway-server
    container_name: gateway-server
    build:
      context: infra/gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  user-service:
    build:
      context: core/user-service
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=udb
      - SPRING_DATASOURCE_PASSWORD=password
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/USER-SERVICE || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      user-db:
        condition: service_healthy

  event-service:
    build:
      context: core/event-service
      dockerfile: Dockerfile
    image: event-service
    container_name: event-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_PROFILE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event-db
      - SPRING_DATASOURCE_USERNAME=edb
      - SPRING_DATASOURCE_PASSWORD=password
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/EVENT-SERVICE || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      event-db:
        condition: service_healthy

  request-service:
    build:
      context: core/request-service
      dockerfile: Dockerfile
    image: request-service
    container_name: request-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/request-db
      - SPRING_DATASOURCE_USERNAME=rdb
      - SPRING_DATASOURCE_PASSWORD=password
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/REQUEST-SERVICE || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      request-db:
        condition: service_healthy

  comment-service:
    build:
      context: core/comment-service
      dockerfile: Dockerfile
    image: comment-service
    container_name: comment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-db:5432/comment-db
      - SPRING_DATASOURCE_USERNAME=cdb
      - SPRING_DATASOURCE_PASSWORD=password
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/COMMENT-SERVICE || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      comment-db:
        condition: service_healthy

  collector:
    image: collector
    container_name: collector
    build:
      context: stats/collector
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server
      - APP_KAFKA_SERVER=kafka:29092
      - APP_KAFKA_USER_ACTION_TOPIC=stats.user-actions.v1
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/COLLECTOR || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy

  aggregator:
    image: aggregator
    container_name: aggregator
    build:
      context: stats/aggregator
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID=config-server

      - AGGREGATOR_KAFKA_PRODUCER_TOPIC=stats.events-similarity.v1
      - AGGREGATOR_KAFKA_PRODUCER_PROPERTIES_BOOTSTRAP_SERVERS=kafka:29092
      - AGGREGATOR_KAFKA_PRODUCER_PROPERTIES_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - AGGREGATOR_KAFKA_PRODUCER_PROPERTIES_VALUE_SERIALIZER=ru.practicum.serialization.GeneralAvroSerializer
      - AGGREGATOR_KAFKA_PRODUCER_PROPERTIES_ACKS=all
      - AGGREGATOR_KAFKA_PRODUCER_PROPERTIES_ENABLE_IDEMPOTENCE=true

      - AGGREGATOR_KAFKA_CONSUMER_TOPICS_0=stats.user-actions.v1
      - AGGREGATOR_KAFKA_CONSUMER_POLL_TIMEOUT=1s
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_BOOTSTRAP_SERVERS=kafka:29092
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_GROUP_ID=aggregator-similarity
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_KEY_DESERIALIZER=org.apache.kafka.common.serialization.LongDeserializer
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_VALUE_DESERIALIZER=ru.practicum.deserialization.UserActionDeserializer
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_AVRO_VALUE_TYPE=ru.practicum.ewm.stats.avro.UserActionAvro
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_ENABLE_AUTO_COMMIT=false
      - AGGREGATOR_KAFKA_CONSUMER_PROPERTIES_AUTO_OFFSET_RESET=earliest
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://discovery-server:8761/eureka/apps/AGGREGATOR || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=event-db
      - POSTGRES_USER=edb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres/event_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=udb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres/user_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=request-db
      - POSTGRES_USER=rdb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres/request_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  comment-db:
    image: postgres:16.1
    container_name: comment-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_DB=comment-db
      - POSTGRES_USER=cdb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres/comment_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
      - "29092:29092" # internal
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:29092" ]
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true