spring:
  application:
    name: main-service
  config:
    import:
      - "optional:configserver:${SPRING_CLOUD_CONFIG_URI}"
      - "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: ${CONFIG_DISCOVERY:true}
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true